import React, { useState, useEffect } from 'react';
import parse from 'html-react-parser';

export default function DocumentationPage() {
    const [docsHtml, setDocsHtml] = useState(null);
    const [error, setError] = useState(null);

    useEffect(() => {
        // Fetch the main index.html file generated by TypeDoc
        fetch('/docs/index.html')
            .then(response => {
                if (!response.ok) {
                    throw new Error('Could not fetch documentation.');
                }
                return response.text();
            })
            .then(htmlString => {
                setDocsHtml(htmlString);
            })
            .catch(err => {
                console.error(err);
                setError('Failed to load documentation.');
            });
    }, []);

    if (error) {
        return <div>{error}</div>;
    }

    // Display a loading message until the content is fetched
    if (!docsHtml) {
        return <div>Loading documentation...</div>;
    }

    return (
        <div className="documentation-container">
            {parse(docsHtml)}
        </div>
    );
}